# Integrate Fortify on Demand Static AppSec Testing (SAST) into your Azure DevOps  pipeline
# The following service connection must be establish before using this job
#   - FoD_AMS
#
# The following task parameter must be defined 
#   - ReleaseId

trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals CO023

steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: 
    FodConnection: 'FOD_AZURE'
    ReleaseOptions: '0'
    ReleaseId: 1542718
    EntitlementSelection: '0'
    Entitlement: 13738
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '0'
    BuildType: 'mvn'
    BuildCommand: 'clean package'
    PolicyFailAction: '0'